[package]
name = "alpha_zoom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baz_core = { git = "https://github.com/dchiquito/boom-and-zoom", version = "0.1.0" }
tch = "0.14.0"
